# Generated by Django 4.0.3 on 2022-03-10 20:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_hash', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Хэш токена')),
                ('tx_hash', models.CharField(max_length=100, verbose_name='Хэш транзакции создания токена')),
                ('media_url', models.URLField(verbose_name='URL изображения')),
                ('owner', models.TextField(max_length=100, verbose_name='Адрес владельца в сети Ethereum')),
            ],
        ),
    ]
